swagger2 formData & request body refs
getkin/kin-openapi pull request #260
Opened 2020-10-21 12:27 UTC by FrancisLennon17

Issue: 
FormData and standard request bodies defined at root level in a swagger 2 definition would fail the conversion as references could not be resolved as they aren't converted correctly.

V2ToV3 changes
- Changed Parameters `in: formData` to convert to schema refs rather than a request body at levels other than the operation level (because it made it easier to be used in references)
- When converting refs, appropriate conversion from `parameters/` to `components/parameters`, `components/requestBodies` or `components/schemas`
- Added `x-formData-name` and `x-originalName` to the conversions for testing purposes (mostly) so that the original names for parameters are used (e.g. the parameter name which is usually lost on conversion at that level).

V3ToV2 changes
- Converting root level schemas to parameters if they have `type: string format: binary` & updating relevant references (restores original names where possible with extension names)
- Converting root level request bodies components to root level parameters

2020-10-21 13:22 UTC, fenollp requested changes
Thanks for going through all this! Looking forward to merging this :)

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +		} else {
```go
		if len(parameters) == 0 {
```
and drop the if above

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +					Ref: strings.Replace(ref, "#/components/schemas/", "#/parameters/", 1),
reassign ref on its own line so the return fits on a single line

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> -		schema.Value.Items = FromV3SchemaRef(v)
schema.Value.Items, _ = FromV3SchemaRef(v, components)

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +		schemaV2, _ := FromV3SchemaRef(v, components)
ditto

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +		schemaV2, _ := FromV3SchemaRef(v, components)
ditto

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +		schemaV2, _ := FromV3SchemaRef(v, components)
ditto

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +				Ref: strings.Replace(ref, "#/components/schemas/", "#/parameters/", 1),
reassign ref again

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +				return nil, errors.New("Could not find a name for request body")
```suggestion
				return nil, errors.New("could not find a name for request body")
```

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +			// If found an available name
```suggestion
```

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +			consumesFormData = true
just break

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +	if consumesFormData {
drop this after doing the above

2020-10-21 13:22 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +		schema, _ := FromV3SchemaRef(mediaType.Schema, &swagger.Components)
```suggestion
		result.Schema, _ = FromV3SchemaRef(mediaType.Schema, &swagger.Components)
```

2020-10-22 10:49 UTC, FrancisLennon17 commented on openapi2conv/openapi2_conv.go
> +		case v3RequestBody != nil || v3Schema != nil:
Having a schema here means that this is a Body or FormData, which were both previous blocked with that error. Throwing a new error `pathItem must not have a schema parameter`

2020-10-22 12:34 UTC, FrancisLennon17 commented on openapi2conv/openapi2_conv.go
> +	re := regexp.MustCompile(`#\/parameters\/(.+)\/?.*`)
https://goplay.space/#q41ZUpo00A8
Using strings.TrimPrefix & strings.Split if that is ok, less LOC

2020-10-22 12:57 UTC, FrancisLennon17 commented
@fenollp would you be ok with me changing the v2Tov3 conversions to add request bodies for each entry in the consumes field? Rather than generating a single multipart/formData or application/json request body ?

2020-10-22 18:53 UTC, fenollp commented
> @fenollp would you be ok with me changing the v2Tov3 conversions to add request bodies for each entry in the consumes field? Rather than generating a single multipart/formData or application/json request body ?

Yes, this makes total sense. Thanks

2020-10-25 09:03 UTC, fenollp requested changes
:ok_hand:

2020-10-25 09:03 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +	pathSections := strings.Split(cleanPath, "/")
```suggestion
	pathSections := strings.SplitN(cleanPath, "/", 1)
```

2020-10-25 09:03 UTC, fenollp commented on openapi2conv/openapi2_conv.go
> +	pathSections := strings.Split(cleanPath, "/")
```suggestion
	pathSections := strings.SplitN(cleanPath, "/", 1)
```

2020-10-26 12:28 UTC, fenollp approved these changes

2020-10-26 12:31 UTC, fenollp commented
LGTM! I believe this is only missing your 
> v2Tov3 [...] add request bodies for each entry in the consumes field

but this can be part of another PR if you'd prefer me to merge this one today.

2020-10-26 12:44 UTC, FrancisLennon17 commented
@fenollp working on that in another PR, I'm happy to merge this!

2020-10-26 12:45 UTC, FrancisLennon17 commented
squashed those commits

2020-10-26 15:04 UTC, merged