Compile pattern on validate
getkin/kin-openapi pull request #375
Opened 2021-06-22 09:17 UTC by alexanderbolgov-ef

2021-06-22 11:03 UTC, fenollp requested changes

2021-06-22 11:03 UTC, fenollp commented on openapi3/schema.go
> +					if err = schema.compilePattern(); err != nil {
Also (as you can tell from the schema in the test) `Type`/`Format` have nothing to do with regexps. You should be checking `Pattern`.

Simply, outside this code block:
```go
	if schema.Pattern == "" {
		if err = schema.compilePattern(); err != nil {
			return err
		}
	}
```

2021-06-24 07:46 UTC, alexanderbolgov-ef commented on openapi3/schema.go
> +					if err = schema.compilePattern(); err != nil {
ok, thanks, will fix that

2021-06-24 10:15 UTC, fenollp approved these changes

2021-06-24 10:16 UTC, merged