discriminator value should verify the type to avoid panic
getkin/kin-openapi pull request #509
Opened 2022-03-13 03:13 UTC by kandaaaaa

With out this check, the request with body like `{"discriminator": null}` or ``{"discriminator": 1}` will simply get panic 
```
interface conversion: interface {} is nil, not string
```

2022-03-13 12:05 UTC, fenollp requested changes
Thanks for this!
Please add regression tests with at least the two example values you mention.

2022-03-13 12:05 UTC, fenollp commented on openapi3/schema.go
> +				if !okcheck {
```suggestion
				if _, okcheck = discriminatorVal.(string); !okcheck {
```

2022-03-13 21:50 UTC, kandaaaaa commented
Will add some regression tests soon

2022-03-14 02:41 UTC, kandaaaaa commented
@fenollp PR updated for a new test case, and minor code update. Thanks

2022-03-14 09:38 UTC, merged