Fix `resolveSchemaRef()` to load correctly an other spec. file referenced by `$ref`
getkin/kin-openapi pull request #583
Opened 2022-08-23 04:42 UTC by masu-mi

# Fix `resolveSchemaRef()` to load correctly an other spec. file referenced by `$ref`

I can't find contribution guidelines. If you know it, would you let me know it?
At the following case, `resolveSchemaRef()` fails to load other spec. files.

* A schema participate a circular reference.
* The schema has references to component's schema in external spec. files.

## Changes

* Add test case: `TestLoadCircularRefFromFile`
* Change `resolveSchemaRef()` to fix it.

## Cause analysis
`resolveSchemaRef()` miss file path's information during recursive resolving schema reference.
For describe, I'm going use following example.

```directory tree
./testdata
    |- a.yml
    |- b.yml
```

```a.yml
components:
  schemas:
    Foo:
      properties:
        bar:
          $ref: "#/components/schemas/Bar"
        foo2:
          $ref: "b.yml#/components/schemas/Foo"
    Bar:
      properties:
        foo:
          $ref: "#/components/schemas/Foo"
```

```b.yml
components:
  schemas:
    Foo:
      properties:
        id:
          type: string
```

Resolving `Foo`, if process load `foo2` before `bar`, it loads with an order as `Foo` -> `Bar` -> `Foo`.
During 2nd loading `Foo` schema, because `loader.resolveComponent()` set a instance with empty Ref field to `resolved`, the process lost file path information.

Because of golang specification, order of for-loop over map is random, I fail to resolve Foo randomly.

2022-08-26 18:00 UTC, fenollp requested changes

2022-08-26 18:00 UTC, fenollp commented on openapi3/load_cicular_ref_with_external_file_test.go
> +	fmt.Printf("%v\n", doc)
Please use package `require` to assert for absence of error above and presence of correctly parsed data here. 

I'll take care of the go119 fmt changes.

2022-08-26 18:21 UTC, fenollp commented
Please rebase on top of https://github.com/getkin/kin-openapi/pull/584

2022-08-29 13:20 UTC, masu-mi commented
@fenollp Thank you for you feedback. I've rebased this PR and update test code to add assertion with `require` package.

2022-08-29 14:28 UTC, merged

2022-08-29 14:30 UTC, fenollp commented
Thanks!