fix: optional defaults
getkin/kin-openapi pull request #662
Opened 2022-11-14 15:13 UTC by orensolo

Adding the option to skip setting default values in the request body after validation.
See https://github.com/getkin/kin-openapi/issues/639

2022-11-15 16:44 UTC, fenollp requested changes

2022-11-15 16:44 UTC, fenollp commented on openapi3filter/options.go
> +	SkipDefaultValueSet bool
Rename to `SkipSettingDefaults` please

2022-11-15 16:44 UTC, fenollp commented on openapi3filter/issue639_test.go
> +				SkipDefaultValueSet: true, // <== false by default, true means doesn't add default values to request body
You can remove that comment :)

2022-11-15 16:44 UTC, fenollp commented on openapi3filter/issue639_test.go
> +			httpReq, _ := http.NewRequest(http.MethodPut, "/items", strings.NewReader(body))
Handle err please

2022-11-17 07:11 UTC, orensolo commented on openapi3filter/options.go
> +	SkipDefaultValueSet bool
fixed

2022-11-17 07:12 UTC, orensolo commented on openapi3filter/issue639_test.go
> +				SkipDefaultValueSet: true, // <== false by default, true means doesn't add default values to request body
done.

2022-11-17 07:12 UTC, orensolo commented on openapi3filter/issue639_test.go
> +			httpReq, _ := http.NewRequest(http.MethodPut, "/items", strings.NewReader(body))
done.

2022-11-21 12:31 UTC, orensolo commented
@fenollp I fixed all your comments. Can you please review again and merge if all OK?

2022-11-22 14:40 UTC, fenollp approved these changes

2022-11-22 14:42 UTC, merged