Refine schema error reason message
getkin/kin-openapi pull request #748
Opened 2023-01-21 22:15 UTC by ori-shalom

This PR adds tests to the behavior that was added in #735.
The purpose of the tests is to verify that the validated value doesn't appear in the `SchemaError.Reason` field.

Additionally, this PR refines the messages in `SchemaError.Reason` and makes sure `Reason` is always set.

2023-01-22 19:18 UTC, fenollp requested changes
LGTM. A few things to fix and we should look into that readOnly fields issue

2023-01-22 19:18 UTC, fenollp commented on openapi3/issue735_test.go
> +		// TODO: uncomment when https://github.com/getkin/kin-openapi/pull/747 is merged
It's merged

2023-01-22 19:18 UTC, fenollp commented on openapi3/issue735_test.go
> +		//	}).WithNoAdditionalProperties(),
We should rename this method to Without... in another PR

2023-01-22 19:18 UTC, fenollp commented on openapi3/schema.go
> +func (schema *Schema) WithNoAdditionalProperties() *Schema {
Well actually in this PR

2023-01-22 19:18 UTC, fenollp commented on openapi3/schema.go
> +	if strings.Trim(schema.Type[:1], "aeiou") == "" {
Please just compare to the few possible values explicitly with a switch statement.

2023-01-22 23:32 UTC, ori-shalom commented
Thanks for the review.
I fixed your comments + rebased and uncommented the `additionalProperties` test.
As for the `readOnly` & `writeOnly` issue, I think we can address in another PR.

2023-01-23 13:13 UTC, fenollp approved these changes

2023-01-23 13:13 UTC, merged