openapi3filter: deepObject array of objects and array of arrays support
getkin/kin-openapi pull request #923
Opened 2024-03-12 15:56 UTC by danicc097

2024-03-13 10:38 UTC, fenollp requested changes
LGTM just one request

2024-03-13 13:58 UTC, danicc097 commented
I don't see any changes? @fenollp

2024-03-13 14:09 UTC, fenollp commented on openapi3filter/req_resp_decoder.go
> +	for i := 0; i <= slices.Max(keys); i++ {
Ah sorry. I probably misstepped and lost the message I was leaving here.

LGTM, just: could you inline this call here? So as to drop the dependency on `x/exp`

2024-03-22 18:37 UTC, fenollp approved these changes

2024-03-22 19:15 UTC, merged